version: '3.1'
services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
    ports:
      - ${PORT}:8181
    volumes:
      - ${PATH}:/config
    restart: always
