version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - TZ=America/Chicago
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - serverIP=${IP} #0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeName=MyInternalNode
    volumes:
      - ${ServerPath}:/app/server
      - ${ConfigsPath}:/app/configs
      - ${LogsPath}:/app/logs
      - /mnt/remote/media:/media
      - /mnt/local/transcode_cache:/temp


# node example
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - TZ=America/Chicago
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - nodeName=MainNode
      - serverIP=${IP} #0.0.0.0
      - serverPort=8266
    volumes:
      - ${ConfigsPath}:/app/configs
      - ${LogsPath}:/app/logs
      - /mnt/remote/media:/media
      - /mnt/local/transcode_cache:/temp
