version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage-christmas
    restart: always
    ports:
      - ${HOMEPAGEPORT}:3000
    volumes:
      - homepage-christmas:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations

volumes:
  homepage-homelab:
    name: homepage-christmas  #Name of existing volume
