version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage-homelab
    restart: always
    ports:
      #- ${HOMEPAGEPORT}:3000
      - 8001:3000
    volumes:
      -	/var/lib/docker/volumes/homepage-homelab/_data:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
